apiVersion: apps/v1
kind: Deployment
metadata:
  name: habit-tracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: habit-tracker
  template:
    metadata:
      labels:
        app: habit-tracker
    spec:
      containers:
        - name: habit-tracker
          image: docker.io/keanuwatts/theclusterflux:habit-tracker  
          imagePullPolicy: Always
      imagePullSecrets:
        - name: dockerhub-secret
---
# sqlite-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: habit-tracker
spec:
  selector:
    app: habit-tracker
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
#ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: habit-tracker
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - habit-tracker.theclusterflux.com
    secretName: theclusterflux
  rules:
  - host: habit-tracker.theclusterflux.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: habit-tracker
            port:
              number: 8080